Added travis conf

diff --git a/bin/runtests b/bin/runtests
--- a/bin/runtests
+++ b/bin/runtests
@@ -1,33 +1,39 @@
 #!/bin/bash
-
-WGET=/usr/bin/wget
-VIDEO_NAME=ed_1024.ogv
-VIDEO_URL=https://archive.org/download/ElephantsDream/$VIDEO_NAME
-
-if [ ! -f videos/$VIDEO_NAME ]
-then
-    echo "For functional tests the following file will be downloaded"
-    echo " > " $VIDEO_URL "(43.5 MB)"
-    echo -n "Are you agree? (Y/n) "
-    read YN
-    if [ -z "$YN" -o "$YN" == "Y" -o "$YN" == "y" ]; then
-        echo "Getting video file..."
-        $WGET -P videos $VIDEO_URL
-    fi
-fi
+tty -s
+RETVAL=$?
 
 echo "Running unitary tests..."
 mocha tests/unit/model.js
 
-if [ -f videos/$VIDEO_NAME ]; then
-    echo "Running functional tests..."
-    if [ "`which chromedriver`" == "" ]; then
-        echo ""
-        echo "The ChromeDriver could not be found on the current PATH."
-        echo "Please download the latest version of the ChromeDriver from"
-        echo "http://chromedriver.storage.googleapis.com/index.html"
-        echo "and ensure it can be found on your PATH."
-    else
-        mocha -t 10000 tests/func/ui.js
+if [ $RETVAL -eq 0 ]; then
+
+    WGET=/usr/bin/wget
+    VIDEO_NAME=ed_1024.ogv
+    VIDEO_URL=https://archive.org/download/ElephantsDream/$VIDEO_NAME
+
+    if [ ! -f videos/$VIDEO_NAME ]
+    then
+        echo "For functional tests the following file will be downloaded"
+        echo " > " $VIDEO_URL "(43.5 MB)"
+        echo -n "Are you agree? (Y/n) "
+        read YN
+        if [ -z "$YN" -o "$YN" == "Y" -o "$YN" == "y" ]; then
+            echo "Getting video file..."
+            $WGET -P videos $VIDEO_URL
+        fi
     fi
+
+    if [ -f videos/$VIDEO_NAME ]; then
+        echo "Running functional tests..."
+        if [ "`which chromedriver`" == "" ]; then
+            echo ""
+            echo "The ChromeDriver could not be found on the current PATH."
+            echo "Please download the latest version of the ChromeDriver from"
+            echo "http://chromedriver.storage.googleapis.com/index.html"
+            echo "and ensure it can be found on your PATH."
+        else
+            mocha -t 10000 tests/func/ui.js
+        fi
+    fi
+
 fi
